import { ArticleListItem } from "../components/ArticleListItem";
import Footer from "../components/Footer";
import Head from "next/head";
import Image from "next/image";
import Profile from "../public/images/image.png";

export default function Home() {
  return (
    <div className="font-sans">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col mx-auto mt-8 mb-0 max-w-lg items-center">
        <Image
          src={Profile}
          alt="Yahav Rosner"
          className="rounded-md shadow-xl grayscale pl-8"
          height={250}
          width={250}
          srcSet={`${Profile} 250w`}
        />
        <div className="bg-white p-3 rounded-md relative bottom-8 flex flex-col items-center shadow-sm">
          <h1 className="font-bold text-xl font-serif">Yahav Rosner</h1>
          <p className="text-sm text-gray-500 font-mono">Developer/Designer</p>
        </div>
      </div>
      <hr className="mb-6 max-w-lg mx-auto" />
      <div className="max-w-lg mx-auto mb-6">
        <h2 className="text-3xl font-bold mb-6">Latest Posts</h2>
        <div className="flex flex-col">
          <ArticleListItem
            title={"Hello World"}
            summary={"Welcome to my blog!"}
            link={"/hello-world"}
          />
        </div>
      </div>
      <div className="max-w-lg mx-auto">
        <h2 className="text-2xl font-bold">Subscribe to the newsletter</h2>
        <p className="my-2">Get emails from me about technology and my latest articles.</p>
        <form className="flex">
        <input type="email" aria-label="Email for newsletter" placeholder="email@example.com" autoComplete="email" required="" className="px-4 py-2 mt-1 block w-full border-gray-300 rounded-md bg-white text-gray-900 dark:text-gray-100 pr-32" />
        <button type="submit" className="bg-sky-300 p-1 text-sm rounded-md>Subscribe</button>
        </form>
      </div>
      <hr className="my-6 max-w-lg mx-auto" />
      <Footer />
    </div>
  );
}
